Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    # Use a specyfic IP address for tests
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "forwarded_port", guest: 80, host:8080
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
end